# Generated by Django 4.2.8 on 2023-12-23 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "updated_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mark_as_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=50)),
                (
                    "transmission",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "vehicle",
            },
        ),
    ]
